API-12351: fix omitempty on struct fields[v3.4]
livechat/lc-sdk-go pull request #144
Opened 2023-04-26 11:25 UTC by kacperf531

https://livechatinc.atlassian.net/browse/API-12351

2023-05-10 09:52 UTC, wfabjanczuk requested changes

2023-05-10 09:52 UTC, wfabjanczuk commented on webhooks/structures.go
> +	WorkScheduler        *configuration.WorkScheduler `json:"work_scheduler,omitempty"`
```suggestion
	WorkScheduler        configuration.WorkScheduler `json:"work_scheduler,omitempty"`
```
In v3.4 `configuration.WorkScheduler` is a map, which is a pointer field already so there's no need to use pointer here

2023-05-10 09:52 UTC, wfabjanczuk commented on webhooks/structures.go
> +	WorkScheduler        *configuration.WorkScheduler `json:"work_scheduler,omitempty"`
```suggestion
	WorkScheduler        configuration.WorkScheduler `json:"work_scheduler,omitempty"`
```
Same as above

2023-05-11 09:55 UTC, kacperf531 commented on webhooks/structures.go
> +	WorkScheduler        *configuration.WorkScheduler `json:"work_scheduler,omitempty"`
fixed in [API-12351: apply review suggestions](https://github.com/livechat/lc-sdk-go/pull/144/commits/3bdbd1fbf9fad7510a48c7d8f26b5d6531691e32)

2023-05-11 09:55 UTC, kacperf531 commented on webhooks/structures.go
> +	WorkScheduler        *configuration.WorkScheduler `json:"work_scheduler,omitempty"`
fixed in [API-12351: apply review suggestions](https://github.com/livechat/lc-sdk-go/pull/144/commits/3bdbd1fbf9fad7510a48c7d8f26b5d6531691e32)

2023-05-11 10:38 UTC, wfabjanczuk approved these changes

2023-05-11 12:56 UTC, merged