API-7369: Add support for PAT Authorization
livechat/lc-sdk-go pull request #36
Opened 2020-10-01 13:53 UTC by czeczot

* Added TokenType - bearer/basic
* Authorization header created from tokenType and access token
* Added test cases for basic / bearer / invalid token type

2020-10-01 14:16 UTC, litwinow requested changes

2020-10-01 14:16 UTC, litwinow commented on authorization/types.go
> +// Possible values of TokenType.
```suggestion
// Supported values of TokenType.
```

2020-10-01 14:16 UTC, litwinow commented on authorization/types.go
> +// TokenType represents Bearer or Basic authentication scheme.
```suggestion
// TokenType represents authentication scheme.
```

2020-10-01 14:16 UTC, litwinow commented on changelog.md
> +* added TokenType to Token in order to enable authorization by PAT
```suggestion
* Added Type to authorization.Token in order to support different authentication schemes (`Bearer` and `Basic`).
```

2020-10-01 14:16 UTC, litwinow commented on go.sum
> +github.com/livechat/lc-sdk-go v1.0.0 h1:sMIkj3p3emAs9nS4TIjhwhsArxYnPcB60aZgRPt6I2I=
pls remove

2020-10-01 14:16 UTC, litwinow commented on agent/api_test.go
> +		}
you could extract it into functor and pass it as argument to `createAuthorizationHeaderChecker` - `createAuthorizationHeaderChecker` doesn't need to have knowledge of all supported test cases

2020-10-01 14:16 UTC, litwinow commented on agent/api_test.go
> +		}
Also pls have a look at `TestAuthorIDHeader` test - it does very similar stuff to what you want to achieve

2020-10-01 14:26 UTC, kogierman requested changes
+ the stuff that Paweł mentioned

2020-10-01 14:26 UTC, kogierman commented on internal/web_api.go
> +}
please make it a `String()` method with `TokenType` as receiver, then you can simply pass it to `fmt.Sprintf`

2020-10-02 07:14 UTC, czeczot commented on agent/api_test.go
> +}
but NewApi method accepts func without parameters so passing stubGenericTokenGetter won't work

2020-10-02 07:16 UTC, litwinow commented on agent/api_test.go
> +}
`stubGenericTokenGetter` can return function

2020-10-02 11:38 UTC, kogierman approved these changes

2020-10-02 12:05 UTC, litwinow approved these changes

2020-10-05 13:29 UTC, merged