Api 7558 customers retention
livechat/lc-sdk-go pull request #44
Opened 2020-11-20 13:11 UTC by czeczot

2020-11-20 13:59 UTC, kogierman commented on agent/api_test.go
> +		t.Errorf("Invalid limit: %v", total)
limit -> limited customers amount

2020-11-20 13:59 UTC, kogierman commented on agent/api_test.go
> +	customers, total, limit, prevPage, nextPage, rErr := api.ListCustomers(100, "page", "asc", "", agent.NewCustomersFilters())
limit -> limited

2020-11-20 15:43 UTC, kogierman approved these changes

2020-11-23 08:49 UTC, kogierman approved these changes

2020-11-23 10:42 UTC, litwinow requested changes

2020-11-23 10:42 UTC, litwinow commented on agent/api_test.go
> +		t.Errorf("Invalid limited customers amount: %v", total)
```suggestion
		t.Errorf("Invalid limited customers amount: %v", limited)
```

2020-11-23 10:42 UTC, litwinow commented on agent/internal.go
> +	LimitedCustomers uint               `json:"limited_customers,omitempty"`
`,omitempty` not needed, it doesn't do anything on unmarshalling

2020-11-23 13:04 UTC, litwinow approved these changes

2021-01-14 07:34 UTC, czeczot commented
already merged

2021-01-14 07:34 UTC, closed without merging