API-7907: allign changes
livechat/lc-sdk-go pull request #55
Opened 2021-01-13 15:59 UTC by czeczot

2021-01-14 06:26 UTC, lpmichalik approved these changes

2021-01-14 06:26 UTC, lpmichalik commented on configuration/internal.go
> +	BotID  string   `json:"bot_agent_id"`
json:id ?

2021-01-14 07:03 UTC, czeczot commented on configuration/internal.go
> +	BotID  string   `json:"bot_agent_id"`
done

2021-01-14 07:03 UTC, czeczot commented
https://livechatinc.atlassian.net/browse/API-7905

2021-01-14 07:16 UTC, janowsiany requested changes

2021-01-14 07:16 UTC, janowsiany commented on configuration/structures.go
> +}
What about `work_scheduler`,  `groups`, `job_title`, `mobile`, `max_chats_count`, `owner_client_id `

2021-01-14 07:16 UTC, janowsiany commented on configuration/structures.go
> +	Webhooks             *BotWebhooks   `json:"webhooks"`
What about `work_scheduler`, `job_title`, `mobile`

2021-01-14 07:16 UTC, janowsiany commented on configuration/structures.go
> +	Avatar string `json:"avatar_path"`
In Agent structure this field is called AvatarPath, shouldn't we align it as well?

2021-01-15 08:43 UTC, janowsiany requested changes
Generally, i am not totally sure but the difference get_bot(BotDetails) and list_bots(Bot) responses is webhooks field which is only available in get_bot method. Could you please confirm that?

2021-01-15 14:53 UTC, czeczot commented
@janowsiany  Additional fields in get_bot response are: DefaultGroupPriority, ClientID and Webhooks.

2021-01-15 15:02 UTC, janowsiany approved these changes

2021-01-21 07:53 UTC, janowsiany approved these changes

2021-01-26 10:46 UTC, kogierman approved these changes

2021-01-29 08:27 UTC, janowsiany approved these changes

2021-01-29 08:44 UTC, merged