Api 8004 api calls statistics
livechat/lc-sdk-go pull request #59
Opened 2021-01-27 18:25 UTC by czeczot

2021-01-28 11:02 UTC, kogierman requested changes
Generally looks good, I would only like the channel to be passed from outside (similar to i.e. RetryFunc) by SDK consumer, not hardcoded in constructor. This way we are more consistent with "middlewares" convention applied here and also we can avoid needlessly writing to channel when user doesn't care about this data.

2021-01-28 11:14 UTC, litwinow reviewed
pls use one-direction channels, also you can send whole structs and not pointers if the structs are lightweight (`APICallStats` is lightweight because it only has `string` [passed as pointer], `bool` and `time.Duration` which is type alias for `int64`)

2021-01-28 16:10 UTC, kogierman commented on internal/web_api.go
> +	}
oneline: `a.s.sample(metrics.APICallStats{"upload_file", executionTime, err == nil})`

2021-01-28 16:10 UTC, kogierman commented on internal/web_api.go
> +	}
oneline

2021-01-28 16:11 UTC, kogierman requested changes

2021-01-28 16:11 UTC, kogierman commented on internal/web_api.go
> +	}
#crit check if channel is even set :D

2021-01-28 16:23 UTC, litwinow commented on internal/web_api.go
> +	s                    *stats
IMO this `stats` struct is not needed, doesn't provide any value. `sampleChan` could be member of `api` struct and `sample` it's function

2021-01-28 19:45 UTC, litwinow approved these changes

2021-01-28 19:45 UTC, litwinow commented on agent/api.go
> +	SetSampleChannel(chan<- metrics.APICallStats)
OPT: `SetStatsSink`

2021-01-28 19:45 UTC, litwinow commented on internal/web_api.go
> +	sampleChan           chan<- metrics.APICallStats
OPT: `statsSink`

2021-02-02 08:52 UTC, kogierman approved these changes

2021-02-02 11:48 UTC, litwinow commented on agent/api.go
> +	SetStatsSink(f func(metrics.APICallStats))
Use `StatsSinkFunc` everywhere

2021-02-02 11:48 UTC, litwinow commented on internal/web_api.go
> +type StatsSinkFunc func(data metrics.APICallStats)
`data` -> `callStats`

2021-02-02 11:48 UTC, litwinow commented on internal/web_api.go
> +// requests action type, execution time of request and status of the request
don't need to describe what `APICallStats` is here, it should be described where it's defined

2021-02-02 11:48 UTC, litwinow commented on internal/web_api.go
> +	}
set `a.StatsSink` to no-op func in the constructor of API and don't check for `nil` here

2021-02-02 15:23 UTC, litwinow approved these changes

2021-02-02 15:23 UTC, litwinow commented on internal/web_api.go
> +// It accepts one argumet: callStats.
```suggestion
// StatsSinkFunc is called after each API method with statistics of that method execution.
```

2021-02-03 07:54 UTC, kogierman approved these changes

2021-02-03 07:59 UTC, merged