Api 8118 separate bots from webhooks
livechat/lc-sdk-go pull request #63
Opened 2021-02-18 16:09 UTC by czeczot

2021-02-22 09:53 UTC, olek-p requested changes

2021-02-22 09:53 UTC, olek-p commented on configuration/structures.go
> -	Actions   []*BotWebhookAction `json:"actions"`
In this case, `BotWebhookAction` is no longer used

2021-02-25 11:32 UTC, olek-p approved these changes

2021-03-01 10:53 UTC, kogierman approved these changes

2021-03-03 10:44 UTC, merged