Add update_license/group_properties to confapi
livechat/lc-sdk-go pull request #69
Opened 2021-06-01 11:03 UTC by kogierman

2021-06-01 11:25 UTC, litwinow requested changes

2021-06-01 11:25 UTC, litwinow commented on configuration/api.go
> +// UpdateLicenseProperties updates the properties set within a group.
```suggestion
// UpdateGroupProperties updates the properties set within a group.
```

2021-06-02 06:13 UTC, litwinow approved these changes

2021-06-02 06:48 UTC, janowsiany approved these changes

2021-06-02 07:53 UTC, merged